const COOKIE_NAME='gtok';
function parseCookies(req){const out={};(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i<0)return;const k=p.slice(0,i).trim(),v=p.slice(i+1).trim();if(k)out[k]=decodeURIComponent(v)});return out}
function setTokenCookie(res,tok,maxAge){res.setHeader('Set-Cookie',`${COOKIE_NAME}=${encodeURIComponent(JSON.stringify(tok))}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`)}
function clearTokenCookie(res){res.setHeader('Set-Cookie',`${COOKIE_NAME}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`)}
function getTokenFromReq(req){try{return JSON.parse(parseCookies(req)[COOKIE_NAME]||'null')}catch{return null}}
function baseUrl(req){return `${req.headers['x-forwarded-proto']||'https'}://${req.headers.host}`}
function redirectUri(req){return process.env.GOOGLE_REDIRECT_URI||`${baseUrl(req)}/api/oauth-callback`}
async function exchangeCodeForTokens(code,req){const p=new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:redirectUri(req),grant_type:'authorization_code'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});if(!r.ok)throw new Error('No se pudo conectar con Google');return r.json()}
async function refreshAccessToken(refresh){const p=new URLSearchParams({refresh_token:refresh,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});if(!r.ok)throw new Error('No se pudo renovar Gmail');return r.json()}
async function getValidAccessToken(req,res){const t=getTokenFromReq(req);if(!t)return null;if(t.expires_at&&Date.now()<t.expires_at-30000)return t.access_token;if(!t.refresh_token)return null;const f=await refreshAccessToken(t.refresh_token);setTokenCookie(res,{access_token:f.access_token,refresh_token:t.refresh_token,expires_at:Date.now()+f.expires_in*1000},2592000);return f.access_token}
async function gmailFetch(path,token,opts={}){const retries=Number(opts.retries||2);for(let attempt=0;;attempt++){const r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/${path}`,{headers:{Authorization:`Bearer ${token}`}});if(r.ok)return r.json();const text=await r.text();const retryable=r.status===429||r.status===403||r.status>=500;if(retryable&&attempt<retries){const wait=Math.min(5000,700*Math.pow(2,attempt))+Math.floor(Math.random()*250);await new Promise(x=>setTimeout(x,wait));continue}throw new Error(`Gmail API ${r.status}: ${text.slice(0,500)}`)}}
function decode(data){if(!data)return '';return Buffer.from(data.replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8')}
function stripHtml(s){return s.replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/p>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim()}
function extractBody(payload){if(!payload)return '';if(payload.mimeType==='text/plain'&&payload.body?.data)return decode(payload.body.data);if(payload.parts){for(const p of payload.parts){if(p.mimeType==='text/plain'&&p.body?.data)return decode(p.body.data)}for(const p of payload.parts){if(p.mimeType==='text/html'&&p.body?.data)return stripHtml(decode(p.body.data))}for(const p of payload.parts){const x=extractBody(p);if(x)return x}}if(payload.body?.data)return payload.mimeType==='text/html'?stripHtml(decode(payload.body.data)):decode(payload.body.data);return ''}
function getHeader(h,n){const x=(h||[]).find(v=>v.name.toLowerCase()===n.toLowerCase());return x?x.value:''}
function attachments(payload,out=[]){if(!payload)return out;if(payload.filename)out.push(payload.filename);(payload.parts||[]).forEach(p=>attachments(p,out));return [...new Set(out)]}
function senderName(from){const m=from.match(/^\s*"?([^"<]+?)"?\s*</);return (m?m[1]:from.split('@')[0]).trim()}
function cleanBody(body){return body.split(/\n/).map(x=>x.trim()).filter(x=>x&&!/^(from|de|para|to|cc|sent|enviado|subject|asunto|date|fecha):/i.test(x)&&!/^[-=]{2,}\s*(forwarded|mensaje reenviado)/i.test(x)).join('\n').slice(0,14000)}
function prettyDomain(domain){const root=(domain||'').toLowerCase().replace(/^www\./,'').split('.')[0]||'';const map={argenper:'Argenper',vmhingenieros:'VMH Ingenieros',sodexo:'Sodexo',bcp:'BCP',cencosud:'Cencosud',apparka:'Apparka',smartfit:'Smart Fit',triathlon:'Triathlon'};return map[root]||root.replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function extractEmails(text=''){return [...new Set((text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[]).map(x=>x.toLowerCase()))]}
function emailDomain(email=''){return email.split('@')[1]?.toLowerCase()||''}
function orgCandidates(subject,from,body){const text=`${from}\n${body}`;const excluded=new Set(['plazacamacho.com.pe','cencosud.com.pe','apparka.pe','gmail.com','googlemail.com','hotmail.com','outlook.com','live.com','yahoo.com']);const emails=extractEmails(text);const seen=new Set();const out=[];for(const e of emails){const d=emailDomain(e);if(!d||excluded.has(d))continue;const org=prettyDomain(d);if(org&&!seen.has(org.toLowerCase())){seen.add(org.toLowerCase());out.push({org,domain:d,email:e})}}return out}
function subjectCompany(subject=''){const s=subject.replace(/^(?:(?:fwd?|rv|re)\s*:\s*)+/i,'').trim();const pats=[/\blocatar(?:io|ia)\s+([A-ZÁÉÍÓÚÑ0-9][A-ZÁÉÍÓÚÑ0-9 .&_-]{2,50})/i,/\b(?:empresa|contratista|proveedor)\s*[:\-]\s*([^\n,;|]{2,60})/i];for(const re of pats){const m=s.match(re);if(m)return m[1].replace(/\s+-.*$/,'').trim()}return ''}
function detectLocal(subject='',body='',empresa=''){const text=`${subject}\n${body}`;const explicit=text.match(/(?:local|tienda|sede|ubicaci[oó]n)\s*[:\-]\s*([^\n,;]{2,70})/i);if(explicit)return explicit[1].trim();const locat=subject.match(/\blocatar(?:io|ia)\s+([^\n\-]{2,60})/i);if(locat)return locat[1].trim();if(/\bsmart\s*fit\b/i.test(text)&&/\bcamacho\b/i.test(text))return 'Smart Fit Camacho';if(/\bBCP(?:AG)?\b/i.test(text)&&/\bCAMACHO\b/i.test(text))return 'BCP Camacho';if(/\btriathlon\b/i.test(text))return 'Triathlon';if(/\bargenper\b/i.test(subject))return 'Argenper';if(/\bplaza\s*camacho\b/i.test(text))return 'PlazaCamacho';return null}
function pickCompany(subject,from,body){const text=`${subject}\n${body}`;const explicit=text.match(/(?:empresa|contratista|proveedor)\s*[:\-]\s*([^\n,;]{2,60})/i);if(explicit)return explicit[1].trim();const subj=subjectCompany(subject);if(subj)return subj;const candidates=orgCandidates(subject,from,body);if(candidates.length){const forwarded=(body.match(/(?:^|\n)\s*(?:From|De)\s*:\s*[^\n<]*<([^>]+)>/i)||[])[1];if(forwarded){const fd=emailDomain(forwarded);const fc=candidates.find(c=>c.domain===fd);if(fc)return fc.org}const subjectLower=subject.toLowerCase();const tokenMatch=candidates.find(c=>{const root=c.domain.split('.')[0].toLowerCase();const short=root.replace(/ingenieros|servicios|service|grupo|peru|sac|sa$/g,'');return (short.length>=3&&new RegExp(`(?:^|[-_/\s])${short}(?:[-_/\s]|$)`,'i').test(subjectLower))});if(tokenMatch)return tokenMatch.org;const mentioned=candidates.find(c=>subjectLower.includes(c.org.toLowerCase())||subjectLower.includes(c.domain.split('.')[0]));if(mentioned)return mentioned.org;const senderDomain=emailDomain(extractEmails(from)[0]||'');const senderCandidate=candidates.find(c=>c.domain===senderDomain);if(senderCandidate)return senderCandidate.org;return candidates[0].org}const sender=senderName(from);return sender||'No detectada'}
function heuristicParse(subject,from,body){const text=`${subject}\n${body}`;const empresa=pickCompany(subject,from,body);const local=detectLocal(subject,body,empresa);let fechaSolicitud=null;const dm=text.match(/\b(\d{1,2}\s+de\s+[a-záéíóúñ]+(?:\s+de\s+\d{4})?|\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4})\b/i);if(dm)fechaSolicitud=dm[1];let cleanSubject=subject.replace(/^(?:(?:fwd?|rv|re)\s*:\s*)+/i,'').trim();cleanSubject=cleanSubject.replace(/\s*-\s*Locatari[oa]\s+[^-]+$/i,'').trim();const lines=cleanBody(body).split('\n').filter(l=>l.length>12&&!/^(buenos días|buenas tardes|buenas noches|estimados|saludos|cordialmente)[,. ]*$/i.test(l));let detalle=lines.slice(0,3).join(' ').slice(0,450)||cleanSubject||'Sin detalle detectado';let trabajo=cleanSubject||detalle;if(/retiro\s+de\s+caja\s+fuerte/i.test(text))trabajo='Ingreso de personal para retiro de caja fuerte';else if(/permisos?\s+de\s+accesos?/i.test(subject)&&/\b(?:EXT[-_/ ]?MAN|mantenimiento|VMH)\b/i.test(subject))trabajo='Permiso de acceso para trabajo de mantenimiento';else{const workPatterns=[/(?:trabajo(?:s)?(?:\s+a\s+realizar)?|labor(?:es)?|actividad(?:es)?|servicio|motivo)\s*[:\-]\s*([^\n]{4,180})/i,/(?:solicito|solicitamos|se solicita|brindar facilidades(?: para)?|autorizaci[oó]n(?: para)?|autorizar)\s+([^\n]{4,180})/i];for(const re of workPatterns){const m=text.match(re);if(m){trabajo=m[1].trim().replace(/[.;]+$/,'');break}}}trabajo=trabajo.replace(/^(?:fwd?|rv|re)\s*:\s*/i,'').slice(0,220);let status='Sin clasificar';if(/conforme se brindar[aá] facilidades|confirmad|autorizad|aprobad/i.test(text))status='Confirmado';else if(/solicit|favor|facilidades|requer|permiso/i.test(text))status='Pendiente';return{empresa,local,fechaSolicitud,detalle,trabajo,status}}
async function aiParse(subject,from,body){const key=process.env.ANTHROPIC_API_KEY;if(!key)return null;const prompt=`Analiza TODA la cadena de este correo operativo, incluidos encabezados reenviados (From/De/To/Para/CC/Subject/Asunto) y dominios de correo. Devuelve SOLO JSON válido con: empresa (empresa o contratista que realizará/solicita el trabajo; NO uses PlazaCamacho, Cencosud o Apparka salvo que realmente sean el contratista), trabajo (actividad concreta, máximo 12 palabras), detalle (qué se solicita, máximo 2 oraciones), local (tienda/local/sede donde se ejecutará; por ejemplo 'BCP Camacho' o 'Argenper'; null si no aparece), fechaSolicitud (fecha de ejecución si aparece o null), status (Confirmado, Pendiente o Sin clasificar). Distingue EMPRESA de LOCAL. Ejemplo: si el remitente/cadena es VMH Ingenieros y el asunto dice BCP ... CAMACHO, empresa=VMH Ingenieros y local=BCP Camacho. Si el asunto dice Locatario Argenper y los correos son @argenper.com.pe, empresa=Argenper y local=Argenper.\nDe visible: ${from}\nAsunto: ${subject}\nCuerpo completo:\n${body.slice(0,9000)}`;const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:process.env.ANTHROPIC_MODEL||'claude-sonnet-4-6',max_tokens:500,messages:[{role:'user',content:prompt}]})});if(!r.ok)return null;const d=await r.json();try{return JSON.parse((d.content||[]).map(c=>c.text||'').join('').replace(/```json|```/g,'').trim())}catch{return null}}
function turnoFor(iso,subject='',body=''){const text=`${subject}\n${body}`.toLowerCase();if(/\bfuera\s+de\s+horario\b/i.test(text))return 'Noche';if(/\bdentro\s+de(?:l)?\s+horario\b|\bdentro\s+del\s+horario\b/i.test(text))return 'Día';const timeRes=[/\b(?:a\s+partir\s+de(?:\s+las)?|desde(?:\s+las)?|hora(?:rio)?\s*[:\-]?|a\s+las)\s*(\d{1,2})(?:[:.]([0-5]\d))?\s*(a\.?\s*m\.?|p\.?\s*m\.?)?/gi,/\b(\d{1,2})[:.]([0-5]\d)\s*(a\.?\s*m\.?|p\.?\s*m\.?)?/gi];for(const re of timeRes){let m;while((m=re.exec(text))){let h=Number(m[1]);const ap=(m[3]||'').replace(/[.\s]/g,'');if(ap==='pm'&&h<12)h+=12;if(ap==='am'&&h===12)h=0;if(h>=22)return 'Noche'}}if(!iso)return 'Día';const h=new Date(iso).getHours();const start=Number(process.env.DAY_SHIFT_START||7),end=Number(process.env.DAY_SHIFT_END||19);return h>=start&&h<end?'Día':'Noche'}
function isPromotionalEmail(subject,from,body=''){const text=`${subject}\n${from}\n${body.slice(0,2500)}`.toLowerCase();const operational=/solicitud|autoriza|autorizaci[oó]n|ingreso|facilidades|mercader[ií]a|proveedor|contratista|sctr|trabajo|mantenimiento|personal|visita|retiro|recepci[oó]n|permiso|acceso|atenci[oó]n/i.test(text);if(operational)return false;return /\bsamsung\b|newsletter|bolet[ií]n|promoci[oó]n|publicidad|oferta|descuento|sale\b|cyber\s*(?:wow|days?)|black\s*friday|unsubscribe|cancelar\s+suscripci[oó]n|no\s+deseo\s+recibir|marketing/i.test(text)}
module.exports={setTokenCookie,clearTokenCookie,getTokenFromReq,redirectUri,exchangeCodeForTokens,getValidAccessToken,gmailFetch,extractBody,getHeader,attachments,heuristicParse,aiParse,turnoFor,isPromotionalEmail,cleanBody};
