const COOKIE_NAME='gtok';
function parseCookies(req){const out={};(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i<0)return;const k=p.slice(0,i).trim(),v=p.slice(i+1).trim();if(k)out[k]=decodeURIComponent(v)});return out}
function setTokenCookie(res,tok,maxAge){res.setHeader('Set-Cookie',`${COOKIE_NAME}=${encodeURIComponent(JSON.stringify(tok))}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`)}
function clearTokenCookie(res){res.setHeader('Set-Cookie',`${COOKIE_NAME}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`)}
function getTokenFromReq(req){try{return JSON.parse(parseCookies(req)[COOKIE_NAME]||'null')}catch{return null}}
function baseUrl(req){return `${req.headers['x-forwarded-proto']||'https'}://${req.headers.host}`}
function redirectUri(req){return process.env.GOOGLE_REDIRECT_URI||`${baseUrl(req)}/api/oauth-callback`}
async function exchangeCodeForTokens(code,req){const p=new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:redirectUri(req),grant_type:'authorization_code'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});if(!r.ok)throw new Error('No se pudo conectar con Google');return r.json()}
async function refreshAccessToken(refresh){const p=new URLSearchParams({refresh_token:refresh,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});if(!r.ok)throw new Error('No se pudo renovar Gmail');return r.json()}
async function getValidAccessToken(req,res){const t=getTokenFromReq(req);if(!t)return null;if(t.expires_at&&Date.now()<t.expires_at-30000)return t.access_token;if(!t.refresh_token)return null;const f=await refreshAccessToken(t.refresh_token);setTokenCookie(res,{access_token:f.access_token,refresh_token:t.refresh_token,expires_at:Date.now()+f.expires_in*1000},2592000);return f.access_token}
async function gmailFetch(path,token,opts={}){const retries=Number(opts.retries||2);for(let attempt=0;;attempt++){const r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/${path}`,{headers:{Authorization:`Bearer ${token}`}});if(r.ok)return r.json();const text=await r.text();const retryable=r.status===429||r.status===403||r.status>=500;if(retryable&&attempt<retries){const wait=Math.min(5000,700*Math.pow(2,attempt))+Math.floor(Math.random()*250);await new Promise(x=>setTimeout(x,wait));continue}throw new Error(`Gmail API ${r.status}: ${text.slice(0,500)}`)}}
function decode(data){if(!data)return '';return Buffer.from(data.replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8')}
function stripHtml(s){return s.replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/p>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim()}
function extractBody(payload){if(!payload)return '';if(payload.mimeType==='text/plain'&&payload.body?.data)return decode(payload.body.data);if(payload.parts){for(const p of payload.parts){if(p.mimeType==='text/plain'&&p.body?.data)return decode(p.body.data)}for(const p of payload.parts){if(p.mimeType==='text/html'&&p.body?.data)return stripHtml(decode(p.body.data))}for(const p of payload.parts){const x=extractBody(p);if(x)return x}}if(payload.body?.data)return payload.mimeType==='text/html'?stripHtml(decode(payload.body.data)):decode(payload.body.data);return ''}
function getHeader(h,n){const x=(h||[]).find(v=>v.name.toLowerCase()===n.toLowerCase());return x?x.value:''}
function attachments(payload,out=[]){if(!payload)return out;if(payload.filename)out.push(payload.filename);(payload.parts||[]).forEach(p=>attachments(p,out));return [...new Set(out)]}
function senderName(from){const m=from.match(/^\s*"?([^"<]+?)"?\s*</);return (m?m[1]:from.split('@')[0]).trim()}
function cleanBody(body){return body.split(/\n/).map(x=>x.trim()).filter(x=>x&&!/^(from|de|para|to|cc|sent|enviado|subject|asunto|date|fecha):/i.test(x)&&!/^-{2,}\s*(forwarded|mensaje reenviado)/i.test(x)).join('\n').slice(0,12000)}
function heuristicParse(subject,from,body){const text=`${subject}\n${body}`;let empresa=senderName(from);const companyPatterns=[/(?:empresa|contratista|proveedor|cliente|tienda|local)\s*[:\-]\s*([^\n,;]{2,60})/i,/\b(?:de parte de|por parte de)\s+([^\n,;]{2,60})/i];for(const re of companyPatterns){const m=text.match(re);if(m){empresa=m[1].trim();break}}
let local=null;const lm=text.match(/(?:local|tienda|ubicaci[oó]n|sede)\s*[:\-]\s*([^\n,;]{2,70})/i);if(lm)local=lm[1].trim();
let fechaSolicitud=null;const dm=text.match(/\b(\d{1,2}\s+de\s+[a-záéíóúñ]+(?:\s+de\s+\d{4})?|\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4})\b/i);if(dm)fechaSolicitud=dm[1];
const cleanSubject=subject.replace(/^(?:(?:fwd?|rv|re)\s*:\s*)+/i,'').trim();const lines=cleanBody(body).split('\n').filter(l=>l.length>12&&!/^(buenos días|buenas tardes|buenas noches|estimados|saludos|cordialmente)[,. ]*$/i.test(l));let detalle=lines.slice(0,3).join(' ').slice(0,450)||cleanSubject||'Sin detalle detectado';if(cleanSubject&&detalle.toLowerCase()===cleanSubject.toLowerCase())detalle=cleanSubject;
let status='Sin clasificar';if(/confirmad|autorizad|aprobad/i.test(text))status='Confirmado';else if(/solicit|favor|facilidades|requer/i.test(text))status='Pendiente';return{empresa,local,fechaSolicitud,detalle,status}}
async function aiParse(subject,from,body){const key=process.env.ANTHROPIC_API_KEY;if(!key)return null;const prompt=`Analiza este correo operativo de un centro comercial. Devuelve SOLO JSON válido con: empresa (empresa/tienda/contratista involucrado; no uses PlazaCamacho salvo que realmente sea la empresa solicitante), detalle (resumen claro de qué solicita, máximo 2 oraciones), local (local/sede/ubicación si aparece o null), fechaSolicitud (fecha mencionada para ejecutar la solicitud o null), status (Confirmado, Pendiente o Sin clasificar).\nDe: ${from}\nAsunto: ${subject}\nCuerpo: ${body.slice(0,6000)}`;const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:process.env.ANTHROPIC_MODEL||'claude-sonnet-4-6',max_tokens:450,messages:[{role:'user',content:prompt}]})});if(!r.ok)return null;const d=await r.json();try{return JSON.parse((d.content||[]).map(c=>c.text||'').join('').replace(/```json|```/g,'').trim())}catch{return null}}
function turnoFor(iso){if(!iso)return 'Día';const h=new Date(iso).getHours();const start=Number(process.env.DAY_SHIFT_START||7),end=Number(process.env.DAY_SHIFT_END||19);return h>=start&&h<end?'Día':'Noche'}
module.exports={setTokenCookie,clearTokenCookie,getTokenFromReq,redirectUri,exchangeCodeForTokens,getValidAccessToken,gmailFetch,extractBody,getHeader,attachments,heuristicParse,aiParse,turnoFor,cleanBody};
